.github/workflows/deploy-hugo-site.yml
Renamed the default branch from `master` to `main` directly on github.com.
The github workflows also mention the default branch name, hence require updates.
=> fix: Rename master to main

config/_default/hugo.toml
This PR adds Google Analytics measurement ID.
The change is very straightforward, the review is not required.
=> feat: Add google analytics measurement ID

layouts/_default/single.html
Fixes link generation for the author badge in articles. Currently the link generated has an extra `/` that results in a 404 error.
For example [here](https://developer.espressif.com/pages/contribution-guide/content-writing-workflow/) the author link generated is `https://developer.espressif.com//authors/kirill-chalov`.
=> fix(author): Fix link in article to author page

.github/workflows/cron-check-links.yml, .github/workflows/pr-check-file-names.yml, .github/workflows/pr-check-links.yml, .github/workflows/pr-reject-png-jpg.yml
This PR adds a workflow to check if the changes in a PR have PNG and JPEG images. If yes, it blocks the PR for merging and asks to convert the images to WebP.
It also includes other smaller workflows:
- Adds a workflow that rejects filenames with spaces and asks, for example, to replace them with dashes.
- Adds instructions to the existing link checking workflow, because without them, it is not clear now what to do with links that failed automatic checking but are still valid (for example due to CAPTCHA or login requests).
- Adds a cron job to check links in all devportal content on the main branch every Monday.
=> ci: add workflow that rejects merging jpeg and png images

content/blog/build-embedded-swift-application-for-esp32c6/index.md
Added tabs, based on syntax from https://github.com/espressif/developer-portal/pull/68
=> fix: use tabs for Linux/macOS commands

.lycheeignore, content/pages/chip-support-status/esp32c61/index.md
This PR adds the chip support status page for ESP32-C61.
The changes have been reviewed internally.
=> feat: add chip support status for esp32c61

content/pages/chip-support-status/esp32c61/index.md
This feature is displayed by accident. Remove it to be consistent with the current feature list.
The changes have been reviewed internally.
=> fix: remove unpublished feature SCT from esp32c61 support status

README.md, content/pages/contribution-guide/_index.md, content/pages/contribution-guide/content-writing-workflow/index.md, content/pages/contribution-guide/contrib-workflow/index.md, content/pages/contribution-guide/writing-content/index.md
This PR adds the following improvements to the contribution guide:
- Document tabbed code blocks
- Rename _Content contribution workflow_ to _Contribution workflow_ to set its name further apart from _Content writing workflow_
Other changes to be announced later.
=> docs: update contribution guide

.github/workflows/cron-check-links.yml, .github/workflows/pr-check-links.yml
This PR limits link checking by `pr-check-links` to the PR diffs only.
Created an issue in the [lychee-action](https://github.com/lycheeverse/lychee-action/issues/238) repo to collect further feedback.
=> ci: Change workflow pr-check-links to review only the diffs

layouts/partials/article-link/card-related.html, layouts/partials/article-link/card.html
Current state: if shared featured image is set via `featureAsset` it's visible in the article, but it's not visible in the list of articles or in the list of related articles below an article.
The PR adds custom partial for this purpose.
=> Display featureAsset in case of card and card-related

content/blog/esp32-bootstrapping/index.md
Fix the mermaid syntax that was updated with a newer version.
=> fix: article: esp32 bootstrapping

.github/workflows/pr-check-links.yml, .github/workflows/pr-reject-png-jpg.yml, content/blog/making-the-fancy-user-interface-on-esp-has-never-been-easier/index.md
In the `check_links_in_diffs` workflow, the feature branch links are compared to the main branch links. As finalizing changes in a feature branch might take a while, its links get outdated compared to main. This can lead to false positives.
In the proposed updates, the feature branch links are compared to the main branch commit at which the feature branch was created. In this way, the more recent changes in main do not affect link checking.
All links are dumped into `.lycheeignore` from the main branch commit at which the feature branch was created. File names or headings to which the anchor / fragment point might get updated. Yet, checking of fragment links is bypassed. This PR adds steps to identify the files with updated file names and heading titles and removes all links in these …
=> ci[pr-check-links]: dump links from baseline commit for pr link checking

content/blog/espressif-devkits-with-wsl2/index.md
I noticed two small issues with the article about WSL2. Here is the fix for them.
- https://github.com/espressif/developer-portal/pull/149
=> fix: Add simple corrections to the WSL2 article

content/workshops/esp-idf-with-esp32-c6/assignment-1/index.cs.md, content/workshops/esp-idf-with-esp32-c6/assignment-4/index.cs.md, content/workshops/esp-idf-with-esp32-c6/assignment-7/index.cs.md, content/workshops/esp-idf-with-esp32-c6/introduction/index.cs.md
Fixing a couple if bugs in CZ version of ESP32-C6 workshop: 
* Missing CZ version of Introduction
* Missing info about config option to be set in order to work with partition table (https://github.com/espressif/developer-portal/issues/125)
* A bunch of smaller typos and bugs
Fixes https://github.com/espressif/developer-portal/discussions/329
Tested locally with `hugo server`.
=> fix(C6-WS): Fix typos and nitpicks in ESP32-C6 workshop

content/blog/zephyr-rtos-on-esp32-first-steps/index.md
Fix Zephyr initial commands by removing command that no longer exist.
=> blog: Zephyr ROTS: fix init commands

.github/workflows/pr-build-preview.yml, .github/workflows/pr-deploy-preview.yml
Following #348 , this PR splits `pr-deploy-preview` into `pr-build-preview` and `pr-deploy-preview` to adjust access permissions so that fork PRs can be deployed for preview safely.
#348
- Testing to be done
---
=> feat: add separate workflows to build and deploy preview pr

.github/workflows/pr-build-preview.yml, .github/workflows/pr-deploy-preview.yml
This PR adds the logic to pass the PR number from `build-preview` to `deploy-preview` via artifacts due to the issue [GitHub Action pull_request attribute empty in workflow_run event object for PR from forked repo](https://github.com/orgs/community/discussions/25220).
- #43 
- #347 and other PRs listed there
Testing was done in this [PR](https://github.com/f-hollow/developer-portal/pull/2)
---
=> ci(preview): pass PR number to deploy-preview via artifacts

content/blog/nuttx-getting-started/index.md
Change on nuttx getting started article. Suggestion came from @georgik
=> Changes on nuttx getting started article

README.md, content/workshops/flowcode/index.md
=> display author of Flowcode workshop

content/blog/july-2019/index.md
This PR fixes a link that the workflow `Check links in diffs` identifies as a false positive:
`https://www.dfrobot.com/index.php?route=information%2Finformation&information_id=4`
Even though it is, the diffs don't include this change, so this workflow should not report it.
There are two issues that I noticed with regard to this link:
- If `?` is escaped (`\?`), it resolves the issue, but there are many other links with question marks that are not reported... Not sure why it happens yet.
- If I compare checksums of all files in `public/`, the file containing this link was reported as updated, however there were no changes in commits. There might be issues where Hugo updates this file for some reason.
This is not the only case where such things happened:
- Workflow: …
=> feat: fix invalid dfrobot link

.github/workflows/pr-build-preview.yml, .github/workflows/prw-deploy-preview.yml
This PR adds a workflow that compares checksums for the files described below and syncs the diffs:
- Hugo `public/` files generated in CI for the latest commit
- Hugo `public/` directory already deployed to the S3 bucket
The first preview deployment takes up the same about of time. The subsequent deployments reduced from current 3 minutes to roughly 1 minute.
The aws s3 [sync](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html) command compares files according to their timestamp and size. This syncing approach doesn't work well with CI which generates new files during each and every build. The AWS issue [#9074](https://github.com/aws/aws-cli/issues/9074) explains it all. There are numerous threads where users discuss this and suggest that the sync should be …
=> ci: optimize file syncing with s3

content/blog/apr-2021/index.md, content/blog/espressif-socs-lcd-screens/index.md
The link checking cron job [reported](https://github.com/espressif/developer-portal/actions/runs/12859779808) a number of broken links. This PR fixes all esp-dev-kits links.
=> fix: update invalid links

content/blog/2024/12/zephyr-how-to-use-psram/index.md
ESP_HEAP_SEARCH_ALL_REGIONS is not avalialble in Zephyr, so remove it from documentation.
=> zephyr: psram: remove unused symbol

content/pages/chip-support-status/esp32c61/index.md, layouts/shortcodes/chipstatus.html
The following updates are planned:
- The dynamically fetched file `.md` is turned into `.json` with a number of key-value pairs.
- Features in markdown
- Other projects in markdown
- Timestamp when info was generated
- These fields will be populated in different places of chip support pages.
- #377 
---
=> Update chip support pages

content/_index.md
This PR updates the landing page with a new featured article.
[How to create an ESP-IDF component](https://developer.espressif.com/blog/2024/12/how-to-create-an-esp-idf-component/)
---
=> update: Updated the featured article for Feb 25 landing page

content/pages/chip-support-status/esp32c61/index.md
This PR returns the content that disappeared during the work on #376 . Preview page: [ESP32-C61 support status](https://preview-developer.espressif.com/pr403/pages/chip-support-status/esp32c61/).
The file `ESP32-C61.md` that is dynamically fetched was sliced up into several types of content. We sliced up a newly-generated file which did not have the manually added lines (the `External project` section) in the previous version of `ESP32-C61.md`.
The dynamically fetched content is not visible. We will implement pulling the latest JSON files from the script repo to previews a bit later.
- Issue #377 
Testing has been done locally.
---
=> fix: update chip support content

content/blog/2025/02/rust-esp-hal-beta/index.md
Updates the email at the bottom of the rust beta blog post.
=> email fixup

.github/workflows/mirror-main-to-gitlab.yml
Fix the URL for `mirror-main-to-gitlab.yml`.
- PR #415 
---
=> fix: correct URL for mirror-main-to-gitlab workflow

.github/workflows/mirror-main-to-gitlab.yml
This is a fix for another small issue in the `mirror-main-to-gitlab.yml` workflow.
- PR #415 
---
=> fix: correct bad hostname in mirror-main-to-gitlab workflow

.github/workflows/mirror-main-to-gitlab.yml, .github/workflows/pr-check-links-caller.yml, .github/workflows/pr-check-links-worker.yml, content/blog/espressif-devkits-with-wsl2/index.md, content/blog/espressif-socs-lcd-screens/index.md, content/blog/november-2018/index.md, content/blog/november-2020/index.md
Once `pr-check-links` is run, GitHub CI started returning `Error: Compiled regex exceeds size limit of 10485760 bytes.`.
Apparently, the file `.lycheeignore` contains too many entries causing lychee to construct an oversized regex.
I tried several solutions:
- Tried using `--exclude` for links instead of `.lycheeignore`,however, the pipeline resulted in [failure](https://github.com/f-hollow/developer-portal/actions/runs/13806056036/job/38616947549?pr=8).
- Tried other countless fixes invain
The only working solution appeared to be splitting link checking into several stages:
- `non-blog` - all files in `./content` except for `./content/blog/` and `README.md`
- `blog_0-9a-f` - all files in `./content/blog/[0-9a-f]*/` folders
- `blog_g-z`- all files in `./content/blog/[g-z]*/` folders
- …
=> ci: split link checking into multiple jobs

content/blog/2024/12/zephyr-how-to-use-psram/index.md
This PR comes to update necesary details to use PSRAM with more recent Zephyr versions. It also updates the log results to be consistent with those observed when running the samples with more recent Zephyr versions.
This work also adds a session explaining how to place Zephyr's task stacks in external RAM and the associated risks.
=> Article update: Enabling External PSRAM for Zephyr Applications on ESP32 SoCs

content/blog/2025/03/esp32h2-knob/index.md
This PR fixes a typo.
Related to: #450 
---
=> Fixed typo

.gitlab-ci.yml
This PR syncs the GitLab branch `ci/sync_merge_gitlab_to_github` to GitHub.
The changes have been reviewed internally.
> [!WARNING]
>If, for any reason, changes need be committed directly to the GitHub PR (bypassing GitLab), add in GitLab MR the label `GitHub-Edit`. This will disable GitLab CI sync-merge to prevent overwriting changes on GitHub.
=> Sync Merge: ci/sync_merge_gitlab_to_github

.github/workflows/pr-publishing-dates.yml, archetypes/default.md, content/pages/contribution-guide/writing-content/index.md
This PR updates the following:
- When creating an article using the `hugo new content` command, it won't add a timezone and will default to midnight (UTC+0).
- In the contribution guide instructions, added `YYYY/MM` to `hugo new content` example.
- Implemented CI checks:
- Articles added in `content/blog/` need to be in the current `content/blog/YYYY/MM/` folder
- Articles need to bear today's date without a timezone
> [!NOTE]
> The commit `test: add articles with issues in dates` is for demo purposes only. It will be removed before merging.
The workflow has been thoroughly tested in this PR.
---
=> Ci/add articles in yyyy/mm folder

.github/workflows/pr-article-details.yml, archetypes/blog.md, content/blog/2025/04/esp-fourcc-introduction/index.md
This PR fixes an issue with the author's name spelling.
- PR #475 
Testing done locally.
---
=> fix: correct author name spelling

content/blog/2025/03/nuttx-python-esp32s3/index.md, content/blog/2025/05/nuttx-motor-control-and-sensing/index.md, layouts/shortcodes/bilibili-note.html
This PR syncs the GitLab branch `feat/add_bilibili_links` to GitHub.
This MR adds the following:
- The `bilibili-note` shortcode to include a note with a BiliBili link under a YouTube video.
- Links to two BiliBili videos in the articles below (after clicking a link, scroll down a bit):
- [Running Python on ESP32-S3 with NuttX](https://developer.espressif.com/blog/2025/03/nuttx-python-esp32s3/)
- [NuttX for Motor Control and Sensing: MCPWM and DC Motor Control](https://developer.espressif.com/blog/2025/05/nuttx-motor-control-and-sensing/)
The changes have been reviewed internally.
> [!WARNING]
>If, for any reason, changes need be committed directly to the GitHub PR (bypassing GitLab), add the label \`GitHub-Edit\` in the GitLab MR. This will disable GitLab CI sync-merge to prevent …
=> Sync Merge: feat/add_bilibili_links

.github/workflows/cron-deploy-hugo-site.yml, .github/workflows/deploy-production.yml, .github/workflows/pr-build-preview.yml, .gitlab/ci/build_hugo.yml, layouts/_default/single.html, layouts/partials/hugo-embedded/shortcodes/figure-default.html, layouts/shortcodes/figure.html
This PR updates the versions of the software:
- [Hugo](https://github.com/gohugoio/hugo) from `0.135.0` to `0.147.5` (latest supported by Blowfish v2.86.0)
- [Blowfish theme](https://github.com/nunocoracao/blowfish)
- Fast-forwarded from
- Commit ID: `f037da312028f628e59eee7ef063dfc4edd3d78c`
- Timestamp: `Fri Oct 4 16:01:50 2024 +0100`
- Fast-forwarded to
- Version: `v2.86.0`
- Commit ID: `0b06a64139beba6287e7685f4c810ad4ff772fde`
- Timestamp: `Tue May 27 01:03:33 2025 +0100`
As of now, our project has issues with the `figure` shortcode. Upstream PR [#2210](https://github.com/nunocoracao/blowfish/pull/2210/) has been submitted. As our project needs a fix now, this MR has the following changes:
- Software updated according to the notes above
- Blowfish `figure` shortcode temporarily …
=> Update versions of Hugo and blowfish

content/workshops/esp-idf-advanced/_index.md, content/workshops/esp-idf-advanced/assignment-1-1/index.md, content/workshops/esp-idf-advanced/assignment-1-2/index.md, content/workshops/esp-idf-advanced/assignment-1-3/index.md, content/workshops/esp-idf-advanced/assignment-2-1/index.md, content/workshops/esp-idf-advanced/assignment-2-2/index.md, content/workshops/esp-idf-advanced/assignment-3-1/index.md, content/workshops/esp-idf-advanced/assignment-3-2/index.md, content/workshops/esp-idf-advanced/assignment-3-3/index.md, content/workshops/esp-idf-advanced/assignment-4-1/index.md, content/workshops/esp-idf-advanced/assignment-4-2/index.md, content/workshops/esp-idf-advanced/assignment-4-3/index.md, content/workshops/esp-idf-advanced/lecture-1/index.md, content/workshops/esp-idf-advanced/lecture-2/index.md, content/workshops/esp-idf-advanced/lecture-3/index.md, content/workshops/esp-idf-advanced/lecture-4/index.md, content/workshops/esp-idf-basic/_index.md
This PR fixes grammar and syntax issues, types, etc.
---
=> Esp idf workshops proofread

content/workshops/esp-idf-basic/assignment-1-1/index.md, content/workshops/esp-idf-basic/assignment-1-2/index.md, content/workshops/esp-idf-basic/assignment-2-1/index.md, content/workshops/esp-idf-basic/assignment-2-2/index.md, content/workshops/esp-idf-basic/assignment-2-3/index.md, content/workshops/esp-idf-basic/assignment-3-1/index.md, content/workshops/esp-idf-basic/assignment-3-2/index.md, content/workshops/esp-idf-basic/assignment-3-3/index.md, content/workshops/esp-idf-basic/lecture-1/index.md, content/workshops/esp-idf-basic/lecture-2/index.md, content/workshops/esp-idf-basic/lecture-3/index.md
This PR addresses an issue where relative links in various assignment and lecture files within the `esp-idf-basic` workshop were inconsistent. 
Specifically, this fixes the issue where the "next step" links for each "assignments and lectures" could not be opened.
https://developer.espressif.com/workshops/esp-idf-basic/
=> fix: update relative links in assignments and lectures for consistency
