espressif/developer-portal

- hugo.toml
> fix: Update baseURL to actual domain name

- layouts/_default/single.html
* Fixed the light and dark mode switch
> Fixed Giscus light and dark mode switch

- layouts/_default/single.html
Giscus light and dark mode switch fix.
> Giscus light mode script for Giscus

- config/_default/params.toml
- layouts/_default/single.html
Removed theme switch and auto mode for Giscus color theme
> Removed theme switch and auto mode for Giscus color theme

- assets/css/styles.css
- layouts/partials/header/basic.html
The review has already been done internally. This PR is ready to be merged.
> Improve UX for the website navigation bar

- content/events/summit-brazil-24/index.md
Fix Sympla links issue with redirect
> Fix Sympla links issue with redirect

- content/events/summit-brazil-24/index.md
Brazil Summit Sold-out warning and removed the links
> Brazil Summit Sold-out warning and removed the links

- content/events/devcon24/index.md
- content/events/summit-brazil-24/index.md
Fix broken links on the pre-commit check
> Fix broken links on the pre-commit check

- assets/css/styles.css
Added custom style modification, so that menu is more readable even when backdrop is darker.
> css: fix transparency of dropdown menu

- assets/lib/learn/learn.css
- assets/lib/learn/learn.js
- layouts/partials/head.html
- layouts/partials/learn_custom.html
- layouts/shortcodes/tab.html
- layouts/shortcodes/tabs.html
Hello, in this PR, the tabs functionality from the Learn template was added. You can find more information about it at  https://learn.netlify.app/en/shortcodes/tabs/ 
close #66
> feat: tabs shortcode

- content/_index.md
- content/events/community-autumn-24-czechia-brno/index.md
- content/events/devcon24/index.md
- content/events/summit-brazil-24/index.md
This PR updates the latest events.
N/A
N/A
---
> Events updated

- data/authors/pedro-minatel.json
> Profile typo removed

- content/blog/easily-develop-graphical-user-interfaces-with-mcus/index.md
> remove typo from article

- content/blog/flash-encryption-and-secure-boot/index.md
This PR fixes the article publication date.
---
> Date fixed

- content/_index.md
This PR updates the featured content on the main landing page for October.
---
> Update the featured content for Oct 24

- content/blog/espressif-ide/espressif-ide-3-1-0-release/index.md
This PR adds the link for the Windows installer.
---
> Update on the Espressif IDE: Added the new installer link

- .github/workflows/pr-check-links.yml
- content/blog/wireless-connectivity-solutions-for-esp32-p4/index.md
This PR fixed the wrong date during the migration process.
Closes #143 
---
> Fixed the wrong article date: ESP32-P4 Wireless Solution

- content/_index.md
Removed the Community Meeting Brno from the front page.
---
> Removed past events from the front page

- content/blog/new-features-in-esp-rainmaker/index.md
This PR fixes a typo in the author's name.
---
> Typo fixed in the author's name

- content/pages/chip-support-status/esp32c61/index.md
There is a request to update the ESP32-C61 support status page.
> feat: Update the ESP32-C61 support status page

- content/blog/using-lua-as-esp-idf-component-with-esp32/index.md
We would like to add a link "Blog" to ESP Component Registry with a collection of publications about component registry and the component manager. https://developer.espressif.com/tags/component/
This PR adds "Component" tag to the article about components.
---
> Add Component tag to  article about Lua component

- content/blog/using-lua-as-esp-idf-component-with-esp32/index.md
> fix link for cloning

- content/pages/chip-support-status/esp32test/index.md
- layouts/partials/chip_support_status.html
- layouts/partials/head.html
- layouts/shortcodes/chipstatus.html
The feedback after merging #186 was to use the content in markdown to match the format of the source content. This PR tests if markdown content with shortcodes (:smile:) renders successfully.
- #186 
---
> test: add a page with link to external markdown content

- content/blog/integrating-embedded-swift-and-sdl3-on-esp32/index.md
Update the article based on feedback
> doc: update Embedded Swift article

- content/_index.md
This PR changes the featured article for December 2024.
---
> Landing page updated with a new featured article for December 2024

- content/blog/esp-now-for-outdoor-applications/index.md
- content/blog/reliability-esp-now/index.md
Scheduled to 19th and 20th Dec
> fix dates of article publication of esp-now articles

- content/blog/matter-distributed-compliance-ledger-dcl/index.md
This PR adds a missing part of the article.
- #295
> fix: add missing workflow in matter dcl article

- content/_index.md
This PR updates the landing page with a new featured article [Data transmission reliability over ESP-NOW protocol in indoor environment](http://localhost:1313/blog/reliability-esp-now/).
N/A
N/A
---
> feat: Updated the landing page with a new featured article

- content/blog/esp-now-for-outdoor-applications/index.md
This PR fixes 2 minor issues on the ESP-NOW article.
---
> fix: Fixed some minor issues on the ESP-NOW article

- .gitlab-ci.yml
This PR adds a preview feature for GitLab.
It has been reviewed and tested internally.
- Issue #43 
---
> ci: add job to deploy preview on gitlab

- .github/workflows/mirror-main-to-gitlab.yml
Fix another small issue.
- PR #415 
---
> fix: correct another issue in mirror-main-to-gitlab workflow

- content/_index.md
This PR updates the landing page with a new featured article for March 2025.
The selected article is:
[Introducing ESP LowCode Matter: Simplified Device Development](https://developer.espressif.com/blog/2025/02/introducing-esp-lowcode-matter/)
---
> Landing page update with a new featured article: March 2025

- content/blog/2025/03/news-esp32h2-upgrade/index.md
Add press release about ESP32-H2 upgrade.
Checked links locally - no issues.
---
> blog: add press release about esp32h2 upgrade

- content/blog/2025/03/esp32-bluetooth-clearing-the-air/index.md
> blog: update post for adding a CVE reference

- content/_index.md
This PR will update the landing page and add a second featured article for April 2025.
This PR should be merged only on April 1st.
---
> Landing page update and added a second featured article for April 2025

- content/blog/clion/index.md
In the "[Configuring an ESP-IDF project](https://developer.espressif.com/blog/clion/#configuring-an-esp-idf-project)" section, there is a sentence: "Your project will then start to load. If the process fails, click Reset and Reload Project. It should be Reset Cache and Reload Project.
P.S.: This is a new PR instead of #457, which I closed because of the mess with my commits.
---
> minor fix in the article: Working with ESP-IDF in CLion

- content/blog/2025/03/esp32h2-knob/index.md
- content/blog/2025/04/ulp-lp-core-get-started/index.md
This PR fixes some typoes and other minor things.
---
> fix: typos and other minor things

- content/blog/2025/03/news-esp32h2-upgrade/index.md
- content/blog/2025/05/news-esp32c5-mp/index.md
This article was published at Espressif News: [Espressif's ESP32-C5 is Now in Mass Production](https://www.espressif.com/en/news/ESP32-C5_Mass_Production).
---
> Add ESP32-C5  Mass Production Annoucement

- content/blog/2025/05/news-esp32c5-mp/index.md
Removed link with 404 error.
---
> ESP32-C5 Announcement: Removed links with 404 issue

- content/blog/2025/03/esp32-bluetooth-clearing-the-air/index.md
- data/authors/mahavir-jain.json
> Update the blog post for pointer to software updates

- content/_index.md
This PR updates the featured articles for July 2025 on the landing page.
---
> Updated the featured articles for July 2025

- content/events/summit-brazil-25/index.md
This PR fixes the download link for the ESP32-P4 workshop (Espressif Summit Brazil 2025).
---
> Fix the link for the ESP32-P4 workshop slides

- content/blog/2025/07/esp32-red-da-en18031-compliance-guide-part2/index.md
> Add webinar link to the RED-DA compliance part2 blog

- content/_index.md
This PR updates the landing page with 2 articles from September and updates the featured workshop.
---
> Landing page update with September featured articles

- content/blog/2025/07/esp32-red-da-en18031-compliance-guide-part2/index.md
> Add webinar part2 pointer to RED-DA blog

- content/_index.md
This PR updates the landing page with new articles for October 2025.
---
> Updated the featured articles for October 2025
